### PR TITLE
[TRAVIS] Add newer PHP versions

### PR DESCRIPTION
**Pull request by mfn**
…and also cache composer files, should improve travis installation a bit.

### CODE REVIEW

**Comment by mfn** [comment]
Is travis not properly connected with Github?

The PR triggered a CI run on travis ( https://travis-ci.org/farafiri/PHP-parsing-tool/builds/631667109 ) but I see no "checks" here? 🤔

**Comment by farafiri** [comment]
Can you elaborate? Link you provided looks fine to me.

**Comment by mfn** [comment]
Correct, but here in github, it does not show the integration result:

image

it should show something like 

image

**Comment by farafiri** [comment]
I ll try to fix it when I get some free time

**Pull request merged**
