### PR TITLE
Add a simple boolean operator parser

### PR DESCRIPTION
**Pull request by mfn**
Nothing fancy, just a bit more "examples food", thought it might be helpful

### CODE REVIEW

**Comment by farafiri** [comment]
1. I mot sure if you really meant whiteSpace* all over the places. For example string: "First Order" belong to this grammar.
2. Even if examples presents simple solution they should mention about more advanced ways of solving problem. So I would add info about "caseInsensitive" and "ignoreWhitespaces" flags and string symbol.

PS. I really appreciate test of getErrorString method (I feel like it should have 10x more test than it have now)

**Comment by mfn** [comment]
> caseInsensitive

Good idea!

It's interesting how this changed the error message (from literal to regexp notation, probably exactly to make case-insensitive work => guess on my side, haven't yet dug into that part):
```diff
diff --git a/tests/Examples/BooleanExpressionParserTest.php b/tests/Examples/BooleanExpressionParserTest.php
index 961e757..3d2b044 100644
--- a/tests/Examples/BooleanExpressionParserTest.php
+++ b/tests/Examples/BooleanExpressionParserTest.php
@@ -68,15 +68,15 @@ class BooleanExpressionParserTest extends TestCase
         return [
             [
                 'input' => 'foo or',
-                'error' => "line: 1, character: 7\nexpected: (tokenKeyword|tokenString) or \"(\"\nfound: ",
+                'error' => "line: 1, character: 7\nexpected: (tokenKeyword|tokenString) or /\(/\nfound: ",
             ],
             [
                 'input' => '"foo or',
-                'error' => "line: 1, character: 8\nexpected: \"\\\"\"\nfound: ",
+                'error' => "line: 1, character: 8\nexpected: /\"/\nfound: ",
             ],
             [
                 'input' => 'foo and (bar or baz',
-                'error' => "line: 1, character: 20\nexpected: /\\r\\n|\\n\\r|\\n|\\r|\\s|\\t/ or \")\" or (/\\r\\n|\\n\\r|\\n|\\r|\\s|\\t/* tokenAnd /\\r\\n|\\n\\r|\\n|\\r|\\s|\\t/* expr)\nfound: ",
+                'error' => "line: 1, character: 20\nexpected: /\\r\\n|\\n\\r|\\n|\\r|\\s|\\t/ or /\)/ or (/\\r\\n|\\n\\r|\\n|\\r|\\s|\\t/* tokenAnd /\\r\\n|\\n\\r|\\n|\\r|\\s|\\t/* expr)\nfound: ",
             ],
             [
                 'input' => 'foo not bar',
```

Will look at the other option and update PR later.

**Comment by farafiri** [comment]
caseInsensitive changes text to regex and adds /i to created and existing regexes.

**Comment by mfn** [comment]
> and string symbol.

Good catch!

I was initially having a more complex grammar from a private project featuring also escape sequences (but it's a confidential part, I unfortunately can't share) and overlooked that I can use the more simple built-in `string` now 👍

**Comment by mfn** [comment]
> ignoreWhitespaces

I tried that (and removed the `whiteSpace*` rules), but then this test `\ParserGenerator\tests\Examples\BooleanExpressionParserTest::testParseFail` with the input `foo or` does _not_ fail anymore.

Instead, I see that it has been parsed as `fooor`:
```php

Failed asserting that ParserGenerator\SyntaxTreeNode\Root Object &000000004dc588dd0000000017341470 (
    'beforeContent' => ''
    'type' => 'start'
    'detailType' => 0
    'subnodes' => Array &0 (
        0 => ParserGenerator\SyntaxTreeNode\Branch Object &000000004dc58b500000000017341470 (
            'type' => 'exprOr'
            'detailType' => 0
            'subnodes' => Array &1 (
                0 => ParserGenerator\SyntaxTreeNode\Branch Object &000000004dc58b7e0000000017341470 (
                    'type' => 'exprAnd'
                    'detailType' => 0
                    'subnodes' => Array &2 (
                        0 => ParserGenerator\SyntaxTreeNode\Branch Object &000000004dc58b620000000017341470 (
                            'type' => 'expr'
                            'detailType' => 0
                            'subnodes' => Array &3 (
                                0 => ParserGenerator\SyntaxTreeNode\Leaf Object &000000004dc59ebb0000000017341470 (
                                    'content' => ''
                                    'afterContent' => ''
                                )
                                1 => ParserGenerator\SyntaxTreeNode\Branch Object &000000004dc58b130000000017341470 (
                                    'type' => 'tokenKeyword'
                                    'detailType' => 0
                                    'subnodes' => Array &4 (
                                        0 => ParserGenerator\SyntaxTreeNode\Series Object &000000004dc58b640000000017341470 (
                                            'isWithSeparator' => false
                                            'type' => 'list'
                                            'detailType' => '/[^\s"'()]/'
                                            'subnodes' => Array &5 (
                                                0 => ParserGenerator\SyntaxTreeNode\Leaf Object &000000004dc5889a0000000017341470 (
                                                    'content' => 'f'
                                                    'afterContent' => ''
                                                )
                                                1 => ParserGenerator\SyntaxTreeNode\Leaf Object &000000004dc588de0000000017341470 (
                                                    'content' => 'o'
                                                    'afterContent' => ''
                                                )
                                                2 => ParserGenerator\SyntaxTreeNode\Leaf Object &000000004dc58b6f0000000017341470 (
                                                    'content' => 'o'
                                                    'afterContent' => ' '
                                                )
                                                3 => ParserGenerator\SyntaxTreeNode\Leaf Object &000000004dc58b000000000017341470 (
                                                    'content' => 'o'
                                                    'afterContent' => ''
                                                )
                                                4 => ParserGenerator\SyntaxTreeNode\Leaf Object &000000004dc588c60000000017341470 (
                                                    'content' => 'r'
                                                    'afterContent' => ''
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                        1 => ParserGenerator\SyntaxTreeNode\Series Object &000000004dc58b650000000017341470 (
                            'isWithSeparator' => false
                            'type' => 'list'
                            'detailType' => ''
                            'subnodes' => Array &6 ()
                        )
                    )
                )
                1 => ParserGenerator\SyntaxTreeNode\Series Object &000000004dc58b510000000017341470 (
                    'isWithSeparator' => false
                    'type' => 'list'
                    'detailType' => ''
                    'subnodes' => Array &7 ()
                )
            )
        )
    )
) is false.
```

Same also for `foo not bar` getting parsed as `Series` => `foonotbar`.

Do you have an idea what I'm missing here?

**Comment by farafiri** [comment]
Will check that tomorrow. I must go sleep right now

**Comment by farafiri** [comment]
ignoreWhitespaces causes simple nodes to consume extra white characters after proper matching text. For example both /abc/ and "abc" will consume "abc" and "abc  ".  So in ignoreWhitespaces ("a" "a") is diffrent than "aa" ("a" "a" will match "a a" while "aa" will not match "a a").

In this case /[^\s"'()]/+ is diffrent than /[^\s"'()]+/

**Comment by mfn** [comment]
> In this case /[^\s"'()]/+ is diffrent than /[^\s"'()]+/

omg! 🤦‍♂️

This has nothing to do with the `ignoreWhitespaces` per se, it's simply a typo. The `+` was never meant to be outside the regex delimiter `/`… but of course it "worked" because `+` is also part of the grammar syntax itself 😄 

Sorry for wasting your time due to this typo (fun fact: I've this "error" in the real application where I extracted it from, too), many thanks!

@farafiri Implemented all your feedback, grammar is much easier to read now 👍

**Pull request merged**
